title: Nicholas Vinco
author: Nicholas Vinco
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is me.

# social links
twitter_username: Nouveos # DO NOT include the @ character, or else the build will fail!
github_username:  nvinco # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
